[package]
name = "shelterwall-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = "0.13.1"
tokio = { version = "1.41.0", features = ["full"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_derive = "1.0.214"
toml = "0.8.19"
log = "0.4.22"
env_logger = "0.11.5"

