activate = false
addr = "127.0.0.1"
port = 1984
log_level = "NOTICE"
xdp = true
netfilter = false
localnets = [
    "127.0.0.0/8",
    "192.168.0.0/16",
    "172.16.0.0/12",
    "10.0.0.0/8",
    "169.254.0.0/16",
    "224.0.0.0/4",
    "::1/128",
    "fc00::/7",
    "fe80::/10",
    "ff00::/8",
]
htable_size = 65536
